SELECT * FROM mtcars;
SELECT model, mpg FROM mtcars WHERE mpg > 20;
SELECT COUNT(*) AS total_cars FROM mtcars;
SELECT cyl, COUNT(*) AS count_by_cyl FROM mtcars GROUP BY cyl;
SELECT cyl, AVG(mpg) AS avg_mpg FROM mtcars GROUP BY cyl;
SELECT model, hp FROM mtcars ORDER BY hp DESC FETCH FIRST 5 ROWS ONLY;
SELECT model, wt FROM mtcars WHERE wt BETWEEN 2.5 AND 3.5;
SELECT model FROM mtcars WHERE cyl IN (4,6) AND am = 1;
SELECT am, AVG(hp) AS avg_hp FROM mtcars GROUP BY am;
SELECT model, (hp / wt) AS power_to_weight FROM mtcars;
SELECT model FROM mtcars WHERE mpg = (SELECT MAX(mpg) FROM mtcars);
SELECT model FROM mtcars WHERE mpg = (SELECT MIN(mpg) FROM mtcars);
SELECT gear, AVG(mpg) AS avg_mpg FROM mtcars GROUP BY gear HAVING AVG(mpg) > 20;
SELECT cyl, SUM(hp) AS total_hp FROM mtcars GROUP BY cyl ORDER BY total_hp DESC;
SELECT model, mpg, LAG(mpg) OVER (ORDER BY mpg) AS prev_mpg FROM mtcars;
SELECT model, mpg, LEAD(mpg) OVER (ORDER BY mpg) AS next_mpg FROM mtcars;
SELECT model, mpg FROM mtcars WHERE hp > (SELECT AVG(hp) FROM mtcars);
SELECT SUM(CASE WHEN am = 1 THEN 1 ELSE 0 END) AS manual_count FROM mtcars;
SELECT model, mpg FROM mtcars WHERE carb >= 4 ORDER BY mpg DESC;
SELECT ROUND(AVG(mpg), 2) AS avg_mpg_rounded FROM mtcars;
SELECT model FROM mtcars WHERE CAST(hp AS DECIMAL) / wt > 60;
SELECT DISTINCT cyl FROM mtcars;
SELECT cyl, MIN(mpg) AS min_mpg, MAX(mpg) AS max_mpg FROM mtcars GROUP BY cyl;
SELECT model FROM mtcars WHERE model LIKE '%Merc%';
SELECT model FROM mtcars WHERE qsec < (SELECT AVG(qsec) FROM mtcars);
SELECT am, cyl, AVG(mpg) AS avg_mpg FROM mtcars GROUP BY am, cyl ORDER BY am, cyl;
SELECT model, hp, wt FROM mtcars WHERE hp > 100 AND wt < 3.0;
SELECT 'high_hp' AS tag, COUNT(*) AS count FROM mtcars WHERE hp > 150 UNION ALL SELECT 'low_hp', COUNT(*) FROM mtcars WHERE hp <= 150;
SELECT model, (mpg * 0.425144) AS km_per_liter FROM mtcars;
SELECT model, mpg FROM mtcars WHERE mpg IS NULL;
SELECT model, hp FROM mtcars WHERE hp BETWEEN 100 AND 200 ORDER BY hp;
SELECT am, COUNT(*) AS count_by_transmission, AVG(mpg) AS avg_mpg FROM mtcars GROUP BY am;
SELECT model, (hp * 1.0 / cyl) AS hp_per_cyl FROM mtcars ORDER BY hp_per_cyl DESC;
SELECT model FROM mtcars WHERE vs = 0;
SELECT model, mpg FROM mtcars WHERE mpg > (SELECT AVG(mpg) FROM mtcars) ORDER BY mpg DESC;
SELECT COUNT(*) AS cars_with_4gears FROM mtcars WHERE gear = 4;
SELECT cyl, COUNT(*) AS cars_with_cyl, AVG(hp) AS avg_hp FROM mtcars GROUP BY cyl HAVING COUNT(*) >= 4;
SELECT model, hp, wt FROM mtcars ORDER BY (hp / wt) DESC FETCH FIRST 10 ROWS ONLY;
SELECT model, mpg, RANK() OVER (ORDER BY mpg DESC) AS mpg_rank FROM mtcars;
SELECT model, mpg FROM mtcars WHERE carb = (SELECT carb FROM mtcars WHERE model = 'Ford Pantera L');
SELECT model, CASE WHEN mpg >= 25 THEN 'efficient' WHEN mpg >= 20 THEN 'moderate' ELSE 'inefficient' END AS efficiency FROM mtcars;
SELECT AVG(hp) OVER (PARTITION BY cyl) AS avg_hp_by_cyl, model, hp FROM mtcars ORDER BY cyl;
SELECT SUM(hp) AS total_hp FROM mtcars WHERE am = 1;
SELECT m1.model FROM mtcars m1 WHERE EXISTS (SELECT 1 FROM mtcars m2 WHERE m2.cyl = m1.cyl AND m2.gear = m1.gear AND m2.mpg > 25);
SELECT model, mpg FROM mtcars WHERE mpg > (SELECT AVG(mpg) FROM mtcars WHERE cyl = mtcars.cyl);
UPDATE mtcars SET mpg = mpg * 1.05 WHERE cyl = 4;
INSERT INTO mtcars (model, mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb) VALUES ('New Car', 22.5, 4, 120.0, 95, 3.9, 2.5, 18.5, 1, 1, 5, 2);
DELETE FROM mtcars WHERE model = 'New Car';
SELECT model, COUNT(*) OVER () AS total_rows FROM mtcars;
SELECT model, mpg FROM mtcars ORDER BY mpg DESC FETCH FIRST 1 ROWS ONLY;